version: "3.3"

services:
  ebindalwasmin:
    build: .
    ports:
        - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ebindalwasmin.tls=true"
      - "traefik.http.routers.ebindalwasmin.tls.certresolver=ebindalwasmin"
      - "traefik.http.routers.ebindalwasmin.rule=Host(`ebindalwasmin.gorun.id`)"
      - "traefik.http.routers.ebindalwasmin.entrypoints=websecure"
    restart: always
    networks: 
      - traefik

networks: 
  traefik:
    external: true