version: "3.3"

services:
  ebindalwasmin:
    build: .
    ports:
        - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ebindalwasmin.tls=true"
      - "traefik.http.routers.ebindalwasmin.tls.certresolver=ebindalwasmin"
      - "traefik.http.routers.ebindalwasmin.rule=Host(`ebindalwasmin.gorun.id`)"
      - "traefik.http.routers.ebindalwasmin.entrypoints=websecure"
    restart: always
    networks: 
      - traefik
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ebindalwasmin'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'GtXgl3ug!Do!'
      MYSQL_ROOT_PASSWORD: 'GtXgl3ug!Do!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:

networks: 
  traefik:
    external: true